/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Karen
 */
public class GUI extends javax.swing.JPanel {
    
      public static void main(String args[]) {
          
      }
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNumNameOutput = new javax.swing.JTextArea();
        getNameBtn = new javax.swing.JButton();
        txtNumInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );

        txtNumNameOutput.setColumns(20);
        txtNumNameOutput.setRows(5);
        jScrollPane1.setViewportView(txtNumNameOutput);

        getNameBtn.setText("Get Name");
        getNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNameBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Input Number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumInput)
                    .addComponent(getNameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(getNameBtn)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNameBtnActionPerformed
        try {
            //get input from box, set to var 'num'
            String numString = txtNumInput.getText();
            int num = Integer.parseInt(numString);
            String numName = null;

            int numSize = numString.length();

            for (int i = 0; i < numSize; i++) {
                int currNum = numString.charAt(i);
                String currNumName = null;
                //check for number 11 to 19 
                if (numSize == 2 || numSize == 5) {

                } else {
                    switch (currNum) {
                        case 1:
                            currNumName = "one";
                            break;
                        case 2:
                            currNumName = "two";
                            break;
                        case 3:
                            currNumName = "three";
                            break;
                        case 4:
                            currNumName = "four";
                            break;
                        case 5:
                            currNumName = "five";
                            break;
                        case 6:
                            currNumName = "six";
                            break;
                        case 7:
                            currNumName = "seven";
                            break;
                        case 8:
                            currNumName = "eigth";
                            break;
                        case 9:
                            currNumName = "nine";
                            break;
                    }
                    //adding current number name to String
                    numString = numString + " " + currNumName;
                    
                    //checking postion and length to choose correct defintion for number
                    String words = null;
                    switch(i){
                        case 0:
                            if(numSize == 3){
                                words = "hundred";
                            }else if(numSize == 4){
                                words = "thousand";
                            }
                            break;
                        case 1:
                            
                            break;
                            
                        case 2:
                            
                            break;
                    }
                    numString = numString + " " + words;
                }

            }

            txtNumNameOutput.setText(numName);
        } catch (NumberFormatException NFex) {
            //if input is not a number
            txtNumInput.setText("Numbers only");
        }
    }//GEN-LAST:event_getNameBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getNameBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNumInput;
    private javax.swing.JTextArea txtNumNameOutput;
    // End of variables declaration//GEN-END:variables
}
